program: wandb_test.py
name: sweepdemo
method: random
metric:
 goal: minimize
 name: Train/Loss
parameters:
 optimizer:
  values: ["adam", "sgd"]
 fc_layer_size:
  values: [128, 256, 512]
 dropout:
  values: [0.3, 0.4, 0.5]
 epochs:
  value: 1
 learning_rate:
  min: 0.01
  max: 0.1
 batch_size:
  distribution: 'q_log_uniform_values'
  q: 8
  min: 32
  max: 256