name: sweep_non_private_maximize_both_val_AUC_minus_FPR
method: grid
metric:
 goal: maximize
 name: both_val_overall_AUC_minus_TPR_gap
parameters:
#  optimizer:
#   values: ["adam", "sgd"]
 epochs:
  values: [50, 75, 100]
 learning_rate:
  values: [0.0005, 0.00075, 0.001]
 seed:
  values: [42]
 batch_size:
  values: [32, 64, 128, 256]
 out_name:
  value: 'nonli-resnet'
 save_root:
  value: 'chexpert_wandb/disease_wandb_sweep_non_private_maximize_both_val_AUC_minus_FPR/'