program: chexpert.disease.nonli.dp.wandb.py
name: sweep_epsilon_1
method: grid
metric:
 goal: minimize
 name: val_loss
parameters:
#  optimizer:
#   values: ["adam", "sgd"]
 epochs:
  values: [5, 10, 15]
 learning_rate:
  values: [0.00075, 0.001, 0.00125]
 EPSILON:
  value: 1
 seed:
  values: [42]
 max_physical_batch_size:
  value: 256
 out_name:
  value: 'nonli-resnetdp-all'
 save_root:
  value: 'chexpert_new/diseasewandb/'