name: sweep_epsilon_0.29_maximize_all_val_AUC_minus_FPR_cooked
method: grid
metric:
 goal: maximize
 name: val_resample_sex_overall_AUC_minus_TPR_gap
parameters:
#  optimizer:
#   values: ["adam", "sgd"]
 epochs:
  values: [50, 75, 100, 125]
 learning_rate:
  values: [0.0005, 0.00075, 0.001, 0.00125]
 EPSILON:
  value: 0.29
 seed:
  values: [42]
 max_physical_batch_size:
  value: 256
 out_name:
  value: 'nonli-resnetdp'
 save_root:
  value: 'chexpert_wandb/disease_wandb_sweep_epsilon_0.29_maximize_all_val_AUC_minus_FPR_cooked/'
