name: sweep_epsilon_1_minvaloss_test_fast
method: grid
metric:
 goal: minimize
 name: val_loss
parameters:
#  optimizer:
#   values: ["adam", "sgd"]
 epochs:
  values: [1, 2, 3, 4, 5]
 learning_rate:
  values: [0.0005, 0.00075, 0.001, 0.00125]
 EPSILON:
  value: 1
 seed:
  values: [42]
 max_physical_batch_size:
  value: 256
 out_name:
  value: 'nonli-resnetdp-all'
 save_root:
  value: 'chexpert_new/diseasewandb_minvalloss_test_fast/'