name: sweep_epsilon_0.1_maximize_val_AUC_minus_FPR
method: grid
metric:
 goal: maximize
 name: overall_AUC_minus_TPR_gap
parameters:
#  optimizer:
#   values: ["adam", "sgd"]
 epochs:
  values: [50, 75, 100, 125]
 learning_rate:
  values: [0.0005, 0.00075, 0.001, 0.00125]
 EPSILON:
  value: 0.1
 seed:
  values: [42]
 max_physical_batch_size:
  value: 256
 out_name:
  value: 'nonli-resnetdp-all'
 save_root:
  value: 'chexpert_wandb/disease_wandb_sweep_epsilon_0.1_maximize_val_AUC_minus_FPR/'
 val_path:
  value: '/vol/aimspace/users/ngq/Towards-Fair-and-Private-AI-in-Chest-Radiograph-Analysis/data/chexpert.sample.val.csv'