name: sweep_non_private_maximize_resample_val_AUC_minus_FPR
method: grid
metric:
 goal: maximize
 name: overall_AUC_minus_TPR_gap
parameters:
#  optimizer:
#   values: ["adam", "sgd"]
 epochs:
  values: [50, 75, 100, 125]
 learning_rate:
  values: [0.0005, 0.00075, 0.001, 0.00125]
 seed:
  values: [42]
 batch_size:
  values: [32, 64, 128, 256]
 out_name:
  value: 'nonli-resnet-all'
 save_root:
  value: 'chexpert_wandb/disease_wandb_sweep_non_private_maximize_resample_val_AUC_minus_FPR/'
 val_path:
  value: '/vol/aimspace/users/ngq/Towards-Fair-and-Private-AI-in-Chest-Radiograph-Analysis/data/chexpert.resample.val.csv'